export const ADD_SHOE_SIZES = "ADD_SHOE_SIZES";
export const ADD_SUBSEQUENT_SHOE_SIZES = "ADD_SUBSEQUENT_SHOE_SIZES";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
